// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name, description) 
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateCollectionParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (*Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return &i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections 
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, description 
FROM collections 
WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id int32) (*Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return &i, err
}

const getCollections = `-- name: GetCollections :many
SELECT id, name, description 
FROM collections 
ORDER BY name
`

func (q *Queries) GetCollections(ctx context.Context) ([]*Collection, error) {
	rows, err := q.db.Query(ctx, getCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections 
SET name = $1, description = $2 
WHERE id = $3
`

type UpdateCollectionParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.Exec(ctx, updateCollection, arg.Name, arg.Description, arg.ID)
	return err
}
