// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToHistory = `-- name: AddToHistory :one
INSERT INTO history (url, method, status_code, duration_ms, timestamp) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id, url, method, status_code, duration_ms, timestamp
`

type AddToHistoryParams struct {
	Url        string      `json:"url"`
	Method     string      `json:"method"`
	StatusCode pgtype.Int4 `json:"status_code"`
	DurationMs pgtype.Int8 `json:"duration_ms"`
	Timestamp  int64       `json:"timestamp"`
}

func (q *Queries) AddToHistory(ctx context.Context, arg AddToHistoryParams) (*History, error) {
	row := q.db.QueryRow(ctx, addToHistory,
		arg.Url,
		arg.Method,
		arg.StatusCode,
		arg.DurationMs,
		arg.Timestamp,
	)
	var i History
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Method,
		&i.StatusCode,
		&i.DurationMs,
		&i.Timestamp,
	)
	return &i, err
}

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM history
`

func (q *Queries) ClearHistory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearHistory)
	return err
}

const deleteHistoryEntry = `-- name: DeleteHistoryEntry :exec
DELETE FROM history 
WHERE id = $1
`

func (q *Queries) DeleteHistoryEntry(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHistoryEntry, id)
	return err
}

const getHistory = `-- name: GetHistory :many
SELECT id, url, method, status_code, duration_ms, timestamp 
FROM history 
ORDER BY timestamp DESC 
LIMIT $1
`

func (q *Queries) GetHistory(ctx context.Context, limit int32) ([]*History, error) {
	rows, err := q.db.Query(ctx, getHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Method,
			&i.StatusCode,
			&i.DurationMs,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryByID = `-- name: GetHistoryByID :one
SELECT id, url, method, status_code, duration_ms, timestamp 
FROM history 
WHERE id = $1
`

func (q *Queries) GetHistoryByID(ctx context.Context, id int32) (*History, error) {
	row := q.db.QueryRow(ctx, getHistoryByID, id)
	var i History
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Method,
		&i.StatusCode,
		&i.DurationMs,
		&i.Timestamp,
	)
	return &i, err
}
