// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type History struct {
	ID         int32       `json:"id"`
	Url        string      `json:"url"`
	Method     string      `json:"method"`
	StatusCode pgtype.Int4 `json:"status_code"`
	DurationMs pgtype.Int8 `json:"duration_ms"`
	Timestamp  int64       `json:"timestamp"`
}

type Request struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Url          string      `json:"url"`
	Method       string      `json:"method"`
	Headers      pgtype.Text `json:"headers"`
	Body         pgtype.Text `json:"body"`
	CollectionID pgtype.Int4 `json:"collection_id"`
}
