// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (name, url, method, headers, body, collection_id) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, url, method, headers, body, collection_id
`

type CreateRequestParams struct {
	Name         string      `json:"name"`
	Url          string      `json:"url"`
	Method       string      `json:"method"`
	Headers      pgtype.Text `json:"headers"`
	Body         pgtype.Text `json:"body"`
	CollectionID pgtype.Int4 `json:"collection_id"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (*Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.Body,
		arg.CollectionID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.Body,
		&i.CollectionID,
	)
	return &i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests 
WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const getAllRequests = `-- name: GetAllRequests :many
SELECT id, name, url, method, headers, body, COALESCE(collection_id, 1) as collection_id
FROM requests 
ORDER BY name
`

type GetAllRequestsRow struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Url          string      `json:"url"`
	Method       string      `json:"method"`
	Headers      pgtype.Text `json:"headers"`
	Body         pgtype.Text `json:"body"`
	CollectionID int32       `json:"collection_id"`
}

func (q *Queries) GetAllRequests(ctx context.Context) ([]*GetAllRequestsRow, error) {
	rows, err := q.db.Query(ctx, getAllRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAllRequestsRow{}
	for rows.Next() {
		var i GetAllRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Body,
			&i.CollectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, name, url, method, headers, body, COALESCE(collection_id, 1) as collection_id
FROM requests 
WHERE id = $1
`

type GetRequestByIDRow struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Url          string      `json:"url"`
	Method       string      `json:"method"`
	Headers      pgtype.Text `json:"headers"`
	Body         pgtype.Text `json:"body"`
	CollectionID int32       `json:"collection_id"`
}

func (q *Queries) GetRequestByID(ctx context.Context, id int32) (*GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.Body,
		&i.CollectionID,
	)
	return &i, err
}

const getRequestsByCollectionID = `-- name: GetRequestsByCollectionID :many
SELECT id, name, url, method, headers, body, COALESCE(collection_id, 1) as collection_id
FROM requests 
WHERE collection_id = $1
ORDER BY name
`

type GetRequestsByCollectionIDRow struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Url          string      `json:"url"`
	Method       string      `json:"method"`
	Headers      pgtype.Text `json:"headers"`
	Body         pgtype.Text `json:"body"`
	CollectionID int32       `json:"collection_id"`
}

func (q *Queries) GetRequestsByCollectionID(ctx context.Context, collectionID pgtype.Int4) ([]*GetRequestsByCollectionIDRow, error) {
	rows, err := q.db.Query(ctx, getRequestsByCollectionID, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRequestsByCollectionIDRow{}
	for rows.Next() {
		var i GetRequestsByCollectionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Body,
			&i.CollectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :exec
UPDATE requests 
SET name = $1, url = $2, method = $3, headers = $4, body = $5, collection_id = $6 
WHERE id = $7
`

type UpdateRequestParams struct {
	Name         string      `json:"name"`
	Url          string      `json:"url"`
	Method       string      `json:"method"`
	Headers      pgtype.Text `json:"headers"`
	Body         pgtype.Text `json:"body"`
	CollectionID pgtype.Int4 `json:"collection_id"`
	ID           int32       `json:"id"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) error {
	_, err := q.db.Exec(ctx, updateRequest,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.Body,
		arg.CollectionID,
		arg.ID,
	)
	return err
}
